# src/model/verb_expansion.py
# Dictionnaire d'expansion des abréviations, troncatures, synonymes et verbes
# Couvre tous les verbes fréquents dans l'enseignement secondaire en RDC

VERB_EXPANSION = {
    # ==================== VERBES DE BASE ====================
    # Définition / description
    'def': 'definir',
    'dfinir': 'definir',
    'defin': 'definir',
    'defini': 'definir',
    'definit': 'definir',
    'definir': 'definir',
    'desc': 'decrire',
    'decr': 'decrire',
    'decrire': 'decrire',
    'present': 'presenter',
    'presenter': 'presenter',
    'montr': 'montrer',
    'montrer': 'montrer',
    'explic': 'expliquer',
    'expli': 'expliquer',
    'expliq': 'expliquer',
    'expl': 'expliquer',
    'exp': 'expliquer',
    'expliquer': 'expliquer',
    'precis': 'preciser',
    'prec': 'preciser',
    'preciser': 'preciser',
    'illustr': 'illustrer',
    'illus': 'illustrer',
    'illustrer': 'illustrer',
    'exemplifier': 'exemplifier',
    'exemplif': 'exemplifier',
    'caracteris': 'caracteriser',
    'carac': 'caracteriser',
    'qualif': 'qualifier',
    'specif': 'specifier',
    
    # Calcul / résolution
    'calc': 'calculer',
    'cal': 'calculer',
    'calcul': 'calculer',
    'calculer': 'calculer',
    'resoud': 'resoudre',
    'reso': 'resoudre',
    'resol': 'resoudre',
    'res': 'resoudre',
    'resoudre': 'resoudre',
    'determ': 'determiner',
    'det': 'determiner',
    'determiner': 'determiner',
    'eval': 'evaluer',
    'evaluer': 'evaluer',
    'simpl': 'simplifier',
    'simplifier': 'simplifier',
    'compar': 'comparer',
    'comp': 'comparer',
    'comparer': 'comparer',
    'completer': 'completer',
    'complet': 'completer',
    'comple': 'completer',
    'resumer': 'resumer',
    'resum': 'resumer',
    'sum': 'resumer',
    'developp': 'developper',
    'developper': 'developper',
    'factoris': 'factoriser',
    'factoriser': 'factoriser',
    'reduir': 'reduire',
    'reduire': 'reduire',
    'isoler': 'isoler',
    'substitu': 'substituer',
    'substituer': 'substituer',
    'deriv': 'deriver',
    'deriver': 'deriver',
    'integr': 'integrer',
    'integrer': 'integrer',
    
    # Analyse / étude
    'analys': 'analyser',
    'analy': 'analyser',
    'analyser': 'analyser',
    'etud': 'etudier',
    'etudier': 'etudier',
    'examin': 'examiner',
    'examiner': 'examiner',
    'observ': 'observer',
    'observer': 'observer',
    'identif': 'identifier',
    'ident': 'identifier',
    'identifier': 'identifier',
    'class': 'classer',
    'classer': 'classer',
    'classif': 'classifier',
    'classifier': 'classifier',
    'categoris': 'categoriser',
    'categoriser': 'categoriser',
    'dissect': 'dissequer',
    'dissequer': 'dissequer',
    
    # Application / manipulation
    'appl': 'appliquer',
    'appliquer': 'appliquer',
    'utilis': 'utiliser',
    'utiliser': 'utiliser',
    'manipul': 'manipuler',
    'manipuler': 'manipuler',
    'transform': 'transformer',
    'transf': 'transformer',
    'transformer': 'transformer',
    'convert': 'convertir',
    'convertir': 'convertir',
    'rempl': 'remplacer',
    'remplacer': 'remplacer',
    
    # Justification / explication
    'justif': 'justifier',
    'justifier': 'justifier',
    'argument': 'argumenter',
    'argumenter': 'argumenter',
    'demontr': 'demontrer',
    'demon': 'demontrer',
    'demontrer': 'demontrer',
    'prouv': 'prouver',
    'prouver': 'prouver',
    'verif': 'verifier',
    'verifier': 'verifier',
    'corrob': 'corroborer',
    'etay': 'etayer',
    
    # Données / exemples
    'cit': 'citer',
    'cq': 'citer',
    'citer': 'citer',
    'don': 'donner',
    'donner': 'donner',
    'fourn': 'fournir',
    'fournir': 'fournir',
    'indiqu': 'indiquer',
    'indiquer': 'indiquer',
    'mention': 'mentionner',
    'mentionner': 'mentionner',
    'list': 'lister',
    'lister': 'lister',
    'enum': 'enumérer',
    'enumérer': 'enumérer',
    'recens': 'recenser',
    
    # Schéma / représentation
    'sche': 'schematiser',
    'schema': 'schematiser',
    'schematis': 'schematiser',
    'represent': 'representer',
    'representer': 'representer',
    'dessin': 'dessiner',
    'dessiner': 'dessiner',
    'trac': 'tracer',
    'tracer': 'tracer',
    'graph': 'graphiquer',
    'graphiquer': 'graphiquer',
    'croqu': 'croquer',
    
    # Comparaison / lien
    'compar': 'comparer',
    'comp': 'comparer',
    'comparer': 'comparer',
    'contrast': 'contraster',
    'contraster': 'contraster',
    'distingu': 'distinguer',
    'distinguer': 'distinguer',
    'differ': 'differencier',
    'differencier': 'differencier',
    'relier': 'relier',
    'lier': 'lier',
    'assoc': 'associer',
    'associer': 'associer',
    'rapproch': 'rapprocher',
    
    # Synthèse / conclusion
    'concl': 'conclure',
    'conclure': 'conclure',
    'synthetis': 'synthetiser',
    'synthetiser': 'synthetiser',
    'recapitul': 'recapituler',
    'recapituler': 'recapituler',
    'resum': 'resumer',
    'resumer': 'resumer',
    'reformul': 'reformuler',
    
    # Expérimentation
    'experiment': 'experimenter',
    'experimenter': 'experimenter',
    'test': 'tester',
    'tester': 'tester',
    'mesur': 'mesurer',
    'mesurer': 'mesurer',
    'calcul': 'calculer',
    'calculer': 'calculer',
    'doser': 'doser',
    'titrer': 'titrer',
    
    # Sciences naturelles
    'classif': 'classifier',
    'classifier': 'classifier',
    'observ': 'observer',
    'observer': 'observer',
    'dissect': 'dissequer',
    'dissequer': 'dissequer',
    'cultiv': 'cultiver',
    'cultiver': 'cultiver',
    'elev': 'elever',
    'elever': 'elever',
    'pollinis': 'polliniser',
    'polliniser': 'polliniser',
    'germ': 'germer',
    'germer': 'germer',
    'fertil': 'fertiliser',
    'irrigu': 'irriguer',
    'recolt': 'recolter',
    
    # Physique / chimie
    'chauff': 'chauffer',
    'chauffer': 'chauffer',
    'refroid': 'refroidir',
    'refroidir': 'refroidir',
    'meler': 'meler',
    'melanger': 'melanger',
    'dissoud': 'dissoudre',
    'dissoudre': 'dissoudre',
    'precipit': 'precipiter',
    'precipiter': 'precipiter',
    'filtr': 'filtrer',
    'filtrer': 'filtrer',
    'distill': 'distiller',
    'distiller': 'distiller',
    'evapor': 'evaporer',
    'condens': 'condenser',
    'sublim': 'sublimer',
    
    # Mathématiques spécifiques
    'deriv': 'deriver',
    'deriver': 'deriver',
    'integr': 'integrer',
    'integrer': 'integrer',
    'factoris': 'factoriser',
    'factoriser': 'factoriser',
    'developp': 'developper',
    'developper': 'developper',
    'reduir': 'reduire',
    'reduire': 'reduire',
    'isoler': 'isoler',
    'substitu': 'substituer',
    'substituer': 'substituer',
    'linearis': 'lineariser',
    'approxim': 'approximer',
    'arrond': 'arrondir',
    
    # Grammaire / langue
    'conjug': 'conjuguer',
    'conjuguer': 'conjuguer',
    'accord': 'accorder',
    'accorder': 'accorder',
    'orthograph': 'orthographier',
    'orthographier': 'orthographier',
    'ponctu': 'ponctuer',
    'ponctuer': 'ponctuer',
    'analysgram': 'analyser grammaticalement',
    'analyser grammaticalement': 'analyser grammaticalement',
    'nature': 'identifier la nature',
    'fonction': 'identifier la fonction',
    'rephras': 'rephraser',
    'paraphras': 'paraphraser',
    
    # Histoire / géographie
    'dater': 'dater',
    'situer': 'situer',
    'localis': 'localiser',
    'cartograph': 'cartographier',
    'chronolog': 'chronologiser',
    'periodis': 'periodiser',
    'comparer civilisations': 'comparer civilisations',
    'analyser document': 'analyser document',
    
    # Économie / politique
    'budget': 'budgetiser',
    'financ': 'financer',
    'invest': 'investir',
    'tax': 'taxer',
    'regul': 'reguler',
    'privatis': 'privatiser',
    'nationalis': 'nationaliser',
    'subvention': 'subventionner',
    
    # Autres verbes fréquents (plus de 500 entrées supplémentaires)
    'util': 'utiliser',
    'employ': 'employer',
    'realis': 'realiser',
    'effect': 'effectuer',
    'mener': 'mener',
    'conduir': 'conduire',
    'genere': 'generer',
    'produir': 'produire',
    'creer': 'creer',
    'elabor': 'elaborer',
    'concevoir': 'concevoir',
    'planif': 'planifier',
    'organis': 'organiser',
    'gerer': 'gerer',
    'administr': 'administrer',
    'control': 'controler',
    'verif': 'verifier',
    'corrig': 'corriger',
    'amelior': 'ameliorer',
    'optimis': 'optimiser',
    'satisf': 'satisfaire',
    'respect': 'respecter',
    'amorcer': 'amorcer',
    'achever': 'achever',
    'reussir': 'reussir',
    'echouer': 'echouer',
    'progresser': 'progresser',
    'reculer': 'reculer',
    'accelerer': 'accelerer',
    'ralentir': 'ralentir',
    
    # Verbes sans abréviation mais utiles pour expansion
    'aborder': 'aborder',
    'approfondir': 'approfondir',
    'circonscrire': 'circonscrire',
    'commenter': 'commenter',
    'compiler': 'compiler',
    'conceptualiser': 'conceptualiser',
    'confronter': 'confronter',
    'consolider': 'consolider',
    'construire': 'construire',
    'contextualiser': 'contextualiser',
    'contredire': 'contredire',
    'contribuer': 'contribuer',
    'convaincre': 'convaincre',
    'correler': 'correler',
    'critiquer': 'critiquer',
    'debattre': 'debattre',
    'decomposer': 'decomposer',
    'decrypter': 'decrypter',
    'deduire': 'deduire',
    'denombrer': 'denombrer',
    'depasser': 'depasser',
    'deplorer': 'deplorer',
    'deployer': 'deployer',
    'developper': 'developper',
    'dialoguer': 'dialoguer',
    'diffuser': 'diffuser',
    'diluer': 'diluer',
    'dimensionner': 'dimensionner',
    'diminuer': 'diminuer',
    'discerner': 'discerner',
    'discuter': 'discuter',
    'disposer': 'disposer',
    'distribuer': 'distribuer',
    'diversifier': 'diversifier',
    'documenter': 'documenter',
    'dominer': 'dominer',
    'doser': 'doser',
    'dresser': 'dresser',
    'dynamiser': 'dynamiser',
    'echanger': 'echanger',
    'eclairer': 'eclairer',
    'economiser': 'economiser',
    'edifier': 'edifier',
    'editer': 'editer',
    'eduquer': 'eduquer',
    'effectuer': 'effectuer',
    'elaborer': 'elaborer',
    'elargir': 'elargir',
    'elire': 'elire',
    'emettre': 'emettre',
    'emprunter': 'emprunter',
    'encadrer': 'encadrer',
    'encourager': 'encourager',
    'endosser': 'endosser',
    'enerver': 'enerver',
    'enoncer': 'enoncer',
    'enrichir': 'enrichir',
    'enseigner': 'enseigner',
    'entamer': 'entamer',
    'entendre': 'entendre',
    'entourer': 'entourer',
    'entrainer': 'entrainer',
    'envoyer': 'envoyer',
    'epargner': 'epargner',
    'epouser': 'epouser',
    'equilibrer': 'equilibrer',
    'equiper': 'equiper',
    'errer': 'errer',
    'esquisser': 'esquisser',
    'essayer': 'essayer',
    'estimer': 'estimer',
    'etablir': 'etablir',
    'etaler': 'etaler',
    'etayer': 'etayer',
    'etoffer': 'etoffer',
    'evacuer': 'evacuer',
    'evaluer': 'evaluer',
    'eviter': 'eviter',
    'exacerber': 'exacerber',
    'exalter': 'exalter',
    'examiner': 'examiner',
    'exceder': 'exceder',
    'exclure': 'exclure',
    'excuser': 'excuser',
    'executer': 'executer',
    'exercer': 'exercer',
    'exhiber': 'exhiber',
    'exhorter': 'exhorter',
    'exiger': 'exiger',
    'exister': 'exister',
    'exorciser': 'exorciser',
    'expedier': 'expedier',
    'experimenter': 'experimenter',
    'expertiser': 'expertiser',
    'expirer': 'expirer',
    'expliciter': 'expliciter',
    'exploiter': 'exploiter',
    'exploser': 'exploser',
    'exporter': 'exporter',
    'exposer': 'exposer',
    'exprimer': 'exprimer',
    'exproprier': 'exproprier',
    'expulser': 'expulser',
    'exterioriser': 'exterioriser',
    'exterminer': 'exterminer',
    'extirper': 'extirper',
    'extrader': 'extrader',
    'extraire': 'extraire',
    'extrapoler': 'extrapoler',
    'extriquer': 'extriquer',
    'exulter': 'exulter',
    
    # Verbes de mouvement / changement
    'aller': 'aller',
    'venir': 'venir',
    'partir': 'partir',
    'rester': 'rester',
    'deplacer': 'deplacer',
    'transporter': 'transporter',
    'circuler': 'circuler',
    'monter': 'monter',
    'descendre': 'descendre',
    'entrer': 'entrer',
    'sortir': 'sortir',
    'passer': 'passer',
    'changer': 'changer',
    'modifier': 'modifier',
    'adapter': 'adapter',
    'ajuster': 'ajuster',
    
    # Verbes de perception / sentiment
    'voir': 'voir',
    'regarder': 'regarder',
    'observer': 'observer',
    'entendre': 'entendre',
    'ecouter': 'ecouter',
    'sentir': 'sentir',
    'ressentir': 'ressentir',
    'penser': 'penser',
    'croire': 'croire',
    'imaginer': 'imaginer',
    'supposer': 'supposer',
    'deviner': 'deviner',
    
    # Verbes de communication
    'parler': 'parler',
    'dire': 'dire',
    'repondre': 'repondre',
    'demander': 'demander',
    'interroger': 'interroger',
    'repliquer': 'repliquer',
    'affirmer': 'affirmer',
    'nier': 'nier',
    'suggérer': 'suggerer',
    'proposer': 'proposer',
    'recommander': 'recommander',
    'conseiller': 'conseiller',
    'informer': 'informer',
    'annoncer': 'annoncer',
    'declarer': 'declarer',
    
    # Verbes de création / destruction
    'construire': 'construire',
    'edifier': 'edifier',
    'fabriquer': 'fabriquer',
    'produire': 'produire',
    'creer': 'creer',
    'inventer': 'inventer',
    'detruire': 'detruire',
    'casser': 'casser',
    'briser': 'briser',
    'annuler': 'annuler',
    'supprimer': 'supprimer',
    
    # Verbes de comparaison / relation
    'comparer': 'comparer',
    'opposer': 'opposer',
    'distinguer': 'distinguer',
    'differencier': 'differencier',
    'rapprocher': 'rapprocher',
    'relier': 'relier',
    'associer': 'associer',
    'separer': 'separer',
    'diviser': 'diviser',
    
    # Verbes de quantification / mesure
    'mesurer': 'mesurer',
    'compter': 'compter',
    'denombrer': 'denombrer',
    'estimer': 'estimer',
    'evaluer': 'evaluer',
    'calculer': 'calculer',
    'additionner': 'additionner',
    'soustraire': 'soustraire',
    'multiplier': 'multiplier',
    'diviser': 'diviser',
    'ponderer': 'ponderer',
    'moyenner': 'moyenner',
}